<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/models/Iphone15.glb')

  const component = forwardEventHandlers()

  const positionCorrection = 0.55
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 1.83, -0.55 + positionCorrection]} scale={[0.1, 1.65, 0.8]}>
      <T.Group position={[-1.49, 0.57, -0.62]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0.11, 0.15, 0.22]}>
        <T.Mesh geometry={gltf.nodes.Object_14.geometry} material={gltf.materials['Material.010']} />
        <T.Mesh geometry={gltf.nodes.Object_15.geometry} material={gltf.materials['Material.019']} />
      </T.Group>
      <T.Group position={[-1.49, 0.82, -0.62]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0.11, 0.15, 0.22]}>
        <T.Mesh geometry={gltf.nodes.Object_17.geometry} material={gltf.materials['Material.010']} />
        <T.Mesh geometry={gltf.nodes.Object_18.geometry} material={gltf.materials['Material.019']} />
      </T.Group>
      <T.Group position={[-1.49, 0.69, -0.1]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[0.11, 0.15, 0.22]}>
        <T.Mesh geometry={gltf.nodes.Object_24.geometry} material={gltf.materials['Material.010']} />
        <T.Mesh geometry={gltf.nodes.Object_25.geometry} material={gltf.materials['Material.019']} />
      </T.Group>
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials['Material.001']} />
      <T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials['Material.002']} />
      <T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials['Material.006']} />
      <T.Mesh geometry={gltf.nodes.Object_7.geometry} material={gltf.materials['Material.007']} />
      <T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials['Material.012']} />
      <T.Mesh
        geometry={gltf.nodes.Object_10.geometry}
        material={gltf.materials['Material.003']}
        position={[0, 0.23, -1.01]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.33, 0.12, 0.02]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_12.geometry}
        material={gltf.materials['Material.004']}
        position={[-1.22, 0.69, -0.36]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.19, 0.27, 0.55]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_20.geometry}
        material={gltf.materials['Material.009']}
        position={[-1.36, 0.5, -0.09]}
        rotation={[-Math.PI, 0, -1.37]}
        scale={[0.05, 0.03, 0.09]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_22.geometry}
        material={gltf.materials.material_0}
        position={[-1.33, 0.83, 0.08]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.01, 0, 0.01]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_27.geometry}
        material={gltf.materials['Material.018']}
        position={[-1.16, 0.68, -0.1]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.33, 0.04, 0.08]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_29.geometry}
        material={gltf.materials['Material.018']}
        position={[-1.16, 0.57, -0.62]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.28, 0.03, 0.07]}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_31.geometry}
        material={gltf.materials['Material.018']}
        position={[-1.16, 0.82, -0.62]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.28, 0.03, 0.07]}
      />
    </T.Group>
    <T.Group position={[-0.09, 3.27, -0.62 + positionCorrection]} rotation={[0, 0, -Math.PI / 2]} scale={0.07}>
      <T.Mesh geometry={gltf.nodes.Object_35.geometry} material={gltf.materials['Material.008']} />
      <T.Mesh geometry={gltf.nodes.Object_36.geometry} material={gltf.materials['Material.011']} />
      <T.Mesh geometry={gltf.nodes.Object_37.geometry} material={gltf.materials['Material.013']} />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Object_33.geometry}
      material={gltf.materials['logo_brand_brands_logos_apple_ios-512']}
      position={[-0.17, 1.86, -0.55 + positionCorrection]}
      rotation={[Math.PI / 2, 0, Math.PI / 2]}
      scale={0.49}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
