<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 src/lib/assets/models/iPhoneCCXTest.glb --types
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-15-pro-black-6fd1283ec05d412d99a3f23b2e80e473
Title: Apple iPhone 15 Pro Black
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
  import iPhoneCCXTest from '../../assets/models/iPhoneCCXTest.glb'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      QlPBYpvqeHJTqvB: THREE.Mesh
      umhWEZbDPozuWiV: THREE.Mesh
      RCJawqKiuRQSLaA: THREE.Mesh
      rwidUyFoomFEexh: THREE.Mesh
      WiCTiUbJRaWYqxO: THREE.Mesh
      GAJNvIndxQKcJlW: THREE.Mesh
      tPkGyFJqvXrCfwU: THREE.Mesh
      CNodxsxObBesPfz: THREE.Mesh
      SHnSyqMisdXMMhR: THREE.Mesh
      XYIXzzOVCeasJpz: THREE.Mesh
      VEytbarjLnxnJPQ: THREE.Mesh
      gEnEhrMJWrtnsYT: THREE.Mesh
      IXktHmDSWKgvarr: THREE.Mesh
      mnajzjnLmbaKpdL: THREE.Mesh
      zVBfXvLpOyyvQgH: THREE.Mesh
      DSGupvmldOCbEbL: THREE.Mesh
      NWIloQeDQHKdVVa: THREE.Mesh
      pYjwTDOhmxmrZmn: THREE.Mesh
      KBIhYXJpJiVODac: THREE.Mesh
      EgPozDYxUhornmK: THREE.Mesh
      GIHTImcRysiycjg: THREE.Mesh
      SsdvaVIEXcsQJKs: THREE.Mesh
      phPOfXVfNSgrUXc: THREE.Mesh
      QXtRJVPAesSsxfF: THREE.Mesh
      mPfnxEkRUoJMHcI: THREE.Mesh
      LmAkTEQLBWAxpSE: THREE.Mesh
      mLHnukkEtKOkORc: THREE.Mesh
      vqfjYxJaPURkbAO: THREE.Mesh
      eClrKxXPYfKSEGr: THREE.Mesh
      zGUfpyhYyXwwIwH: THREE.Mesh
      jnGGkguwjheKNOh: THREE.Mesh
      YhxULnHbuDthdGe: THREE.Mesh
      GrOLxJSnnaGkJfc: THREE.Mesh
      XKBIWBjpFFdQbUy: THREE.Mesh
      fhxaXEhDZvQmEJq: THREE.Mesh
      YQQMWtuDRilWwjr: THREE.Mesh
      VaIdITgcvAEswbE: THREE.Mesh
      AwaTTvzfXeXysUh: THREE.Mesh
      lwKjjNfpnPhIznz: THREE.Mesh
      xWjRzRqRQLipxKp: THREE.Mesh
      CuxrrLMCpabzfLG: THREE.Mesh
      hGBxvFnQASjyqjs: THREE.Mesh
      MdKHIpwWEOYVsvy: THREE.Mesh
      eUDWuQsIBzQvKnr: THREE.Mesh
      fbQSAObXlAFNrTB: THREE.Mesh
      axhbofBzrcPHGNC: THREE.Mesh
      tOcnXdgRVIpvVcJ: THREE.Mesh
      ckthbUCVAlslGwo: THREE.Mesh
      jqzyDcfEWAObzqu: THREE.Mesh
      FtCJydnXEwfnYhk: THREE.Mesh
      yOxTAdtHcqpJQcW: THREE.Mesh
      oNdwLsAMWeVFRHb: THREE.Mesh
      IVUmCkeCMrNjWyf: THREE.Mesh
      oAWGNgCNjsdFObV: THREE.Mesh
      iURsiFzEXHjnluF: THREE.Mesh
      reGnBNbSrWUhgXY: THREE.Mesh
      HvOWnnRtSPSgRpp: THREE.Mesh
      BtxqtHelRBYPNjd: THREE.Mesh
      SnqyBGRajoAqQBo: THREE.Mesh
      KfqydeDluRMVncm: THREE.Mesh
      opZAXkoXMVsPZfx: THREE.Mesh
      MEOAyLvZzdtthOP: THREE.Mesh
      cgCfUEjgOAehctg: THREE.Mesh
      vfgqltUlweTtuUQ: THREE.Mesh
      WsknpEXvcylrpFI: THREE.Mesh
      ySPUcfDKfrAJDkd: THREE.Mesh
      sbwBuXGlPZUuZhO: THREE.Mesh
      eHkjmMEdCbNTHKq: THREE.Mesh
      CvblWIuOYCeiubv: THREE.Mesh
      LiHxzBeBpnvPmqv: THREE.Mesh
      gYxafxocoIVEaqL: THREE.Mesh
      xUWhjfdbAkIxBFR: THREE.Mesh
      oRDDuTkmFDoOGgX: THREE.Mesh
      zEbqYwxrZLBpGwY: THREE.Mesh
      EHsIAxvaWewKLkj: THREE.Mesh
      cVSOhwynzuPTTad: THREE.Mesh
      qXTORrocXUUDbdL: THREE.Mesh
      ronXuqOovjTriZk: THREE.Mesh
      ITpkaLmvkfCQQze: THREE.Mesh
      LHYUrIgekAZIxJn: THREE.Mesh
      fzTRIqQhBOYDYUP: THREE.Mesh
      ETycAkqXtCPSWAW: THREE.Mesh
      bYbpdLBDipjTqaD: THREE.Mesh
      cZZMbxHbRDozLKa: THREE.Mesh
      fBQkcXlqdumyuPk: THREE.Mesh
      rQfrWUmmticZJhs: THREE.Mesh
      QQmFWgkRfIVTarZ: THREE.Mesh
      JFHvDbfOkQKwrQt: THREE.Mesh
      IXQdUQkMawZkTUq: THREE.Mesh
    }
    materials: {
      XeoexknMXFWSvtE: THREE.MeshStandardMaterial
      UfLjSExcWKgJhWH: THREE.MeshStandardMaterial
      cJikWZpcXkRQLHp: THREE.MeshStandardMaterial
      sBkPLofgPxutogi: THREE.MeshStandardMaterial
      gDILPbJhWWMYobZ: THREE.MeshStandardMaterial
      fbSneRIMWKtYaJh: THREE.MeshStandardMaterial
      UMOyvmQQJEoxnTV: THREE.MeshStandardMaterial
      HIKssMsVfsWDqra: THREE.MeshStandardMaterial
      NcddIgyCVqjNBWk: THREE.MeshStandardMaterial
      bPkZQEigsToYyEb: THREE.MeshStandardMaterial
      WzoAyWaaeTXRNVL: THREE.MeshStandardMaterial
      FnknNyMXRxFlncX: THREE.MeshStandardMaterial
      bkznUIsbbfeWYte: THREE.MeshStandardMaterial
      OToSlIITKzBwLBZ: THREE.MeshStandardMaterial
      RsYjwdpNMzmAvJf: THREE.MeshStandardMaterial
      ZVpJkazCvASOIpG: THREE.MeshStandardMaterial
      CyhGvhcPruPQjBl: THREE.MeshStandardMaterial
      sZHQmIZYntplDue: THREE.MeshStandardMaterial
      vTiNuzGBBCKWhjr: THREE.MeshStandardMaterial
      JzwaDHwfoQCENhb: THREE.MeshStandardMaterial
      nZERQganZbJSuaU: THREE.MeshStandardMaterial
      RrnnSedIClmIxYD: THREE.MeshStandardMaterial
      lIkeUCuAgtmXqMm: THREE.MeshStandardMaterial
      jVNrbGhpYeDVmBP: THREE.MeshStandardMaterial
      BUMSUczQGXGkXzw: THREE.MeshStandardMaterial
      bJOIXYmaJBYmLic: THREE.MeshStandardMaterial
      tsbwpbLZoQgeTat: THREE.MeshStandardMaterial
      WwsbjWsUTqkHjyi: THREE.MeshStandardMaterial
      DDTdMXfdNuiuuKY: THREE.MeshStandardMaterial
      lxyVilivCNAAGIX: THREE.MeshStandardMaterial
      XXuRSphlgMABayB: THREE.MeshStandardMaterial
      jaAOvxaOjFCLhAJ: THREE.MeshStandardMaterial
      wvXBYkOjrrFFsaK: THREE.MeshStandardMaterial
      ldlWJWPqNVGUyAp: THREE.MeshStandardMaterial
      otyzQKWDmEsmWNb: THREE.MeshStandardMaterial
      KtouhvwQzJWWPrE: THREE.MeshStandardMaterial
      nYXuzwbAXKNwVVk: THREE.MeshStandardMaterial
      XoueRDhbsAsbeTf: THREE.MeshStandardMaterial
      bUGYdGWBIxjsKUI: THREE.MeshStandardMaterial
      BIXrNIXlGLRYyov: THREE.MeshStandardMaterial
      yCRJxqsYVHIqsxx: THREE.MeshStandardMaterial
      sBkPLofgPxutogi: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>(iPhoneCCXTest)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
        <T.Mesh geometry={gltf.nodes.IXQdUQkMawZkTUq.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.GIHTImcRysiycjg.geometry} material={gltf.materials.bkznUIsbbfeWYte} />
        <T.Mesh geometry={gltf.nodes.SsdvaVIEXcsQJKs.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.phPOfXVfNSgrUXc.geometry} material={gltf.materials.UfLjSExcWKgJhWH} />
        <T.Mesh geometry={gltf.nodes.QXtRJVPAesSsxfF.geometry} material={gltf.materials.OToSlIITKzBwLBZ} />
        <T.Mesh geometry={gltf.nodes.mPfnxEkRUoJMHcI.geometry} material={gltf.materials.NcddIgyCVqjNBWk} />
        <T.Mesh geometry={gltf.nodes.LmAkTEQLBWAxpSE.geometry} material={gltf.materials.RsYjwdpNMzmAvJf} />
        <T.Mesh geometry={gltf.nodes.QlPBYpvqeHJTqvB.geometry} material={gltf.materials.XeoexknMXFWSvtE} />
        <T.Mesh geometry={gltf.nodes.umhWEZbDPozuWiV.geometry} material={gltf.materials.UfLjSExcWKgJhWH} />
        <T.Mesh geometry={gltf.nodes.RCJawqKiuRQSLaA.geometry} material={gltf.materials.cJikWZpcXkRQLHp} />
        <T.Mesh geometry={gltf.nodes.rwidUyFoomFEexh.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.WiCTiUbJRaWYqxO.geometry} material={gltf.materials.gDILPbJhWWMYobZ} />
        <T.Mesh geometry={gltf.nodes.GAJNvIndxQKcJlW.geometry} material={gltf.materials.fbSneRIMWKtYaJh} />
        <T.Mesh geometry={gltf.nodes.tPkGyFJqvXrCfwU.geometry} material={gltf.materials.UMOyvmQQJEoxnTV} />
        <T.Mesh geometry={gltf.nodes.CNodxsxObBesPfz.geometry} material={gltf.materials.HIKssMsVfsWDqra} />
        <T.Mesh geometry={gltf.nodes.VEytbarjLnxnJPQ.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.gEnEhrMJWrtnsYT.geometry} material={gltf.materials.NcddIgyCVqjNBWk} />
        <T.Mesh geometry={gltf.nodes.IXktHmDSWKgvarr.geometry} material={gltf.materials.bPkZQEigsToYyEb} />
        <T.Mesh geometry={gltf.nodes.mnajzjnLmbaKpdL.geometry} material={gltf.materials.bPkZQEigsToYyEb} />
        <T.Mesh geometry={gltf.nodes.zVBfXvLpOyyvQgH.geometry} material={gltf.materials.bPkZQEigsToYyEb} />
        <T.Mesh geometry={gltf.nodes.SHnSyqMisdXMMhR.geometry} material={gltf.materials.NcddIgyCVqjNBWk} />
        <T.Mesh geometry={gltf.nodes.XYIXzzOVCeasJpz.geometry} material={gltf.materials.bPkZQEigsToYyEb} />
        <T.Mesh geometry={gltf.nodes.DSGupvmldOCbEbL.geometry} material={gltf.materials.WzoAyWaaeTXRNVL} />
        <T.Mesh geometry={gltf.nodes.NWIloQeDQHKdVVa.geometry} material={gltf.materials.FnknNyMXRxFlncX} />
        <T.Mesh geometry={gltf.nodes.pYjwTDOhmxmrZmn.geometry} material={gltf.materials.NcddIgyCVqjNBWk} />
        <T.Mesh geometry={gltf.nodes.KBIhYXJpJiVODac.geometry} material={gltf.materials.bPkZQEigsToYyEb} />
        <T.Mesh geometry={gltf.nodes.EgPozDYxUhornmK.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.VaIdITgcvAEswbE.geometry} material={gltf.materials.sZHQmIZYntplDue} />
        <T.Mesh geometry={gltf.nodes.AwaTTvzfXeXysUh.geometry} material={gltf.materials.RrnnSedIClmIxYD} />
        <T.Mesh geometry={gltf.nodes.mLHnukkEtKOkORc.geometry} material={gltf.materials.ZVpJkazCvASOIpG} />
        <T.Mesh geometry={gltf.nodes.vqfjYxJaPURkbAO.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.eClrKxXPYfKSEGr.geometry} material={gltf.materials.CyhGvhcPruPQjBl} />
        <T.Mesh geometry={gltf.nodes.zGUfpyhYyXwwIwH.geometry} material={gltf.materials.sZHQmIZYntplDue} />
        <T.Mesh geometry={gltf.nodes.jnGGkguwjheKNOh.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.YhxULnHbuDthdGe.geometry} material={gltf.materials.vTiNuzGBBCKWhjr} />
        <T.Mesh geometry={gltf.nodes.GrOLxJSnnaGkJfc.geometry} material={gltf.materials.JzwaDHwfoQCENhb} />
        <T.Mesh geometry={gltf.nodes.XKBIWBjpFFdQbUy.geometry} material={gltf.materials.JzwaDHwfoQCENhb} />
        <T.Mesh geometry={gltf.nodes.fhxaXEhDZvQmEJq.geometry} material={gltf.materials.nZERQganZbJSuaU} />
        <T.Mesh geometry={gltf.nodes.YQQMWtuDRilWwjr.geometry} material={gltf.materials.CyhGvhcPruPQjBl} />
        <T.Mesh geometry={gltf.nodes.lwKjjNfpnPhIznz.geometry} material={gltf.materials.lIkeUCuAgtmXqMm} />
        <T.Mesh geometry={gltf.nodes.xWjRzRqRQLipxKp.geometry} material={gltf.materials.jVNrbGhpYeDVmBP} />
        <T.Mesh geometry={gltf.nodes.CuxrrLMCpabzfLG.geometry} material={gltf.materials.BUMSUczQGXGkXzw} />
        <T.Mesh geometry={gltf.nodes.hGBxvFnQASjyqjs.geometry} material={gltf.materials.bJOIXYmaJBYmLic} />
        <T.Mesh geometry={gltf.nodes.MdKHIpwWEOYVsvy.geometry} material={gltf.materials.tsbwpbLZoQgeTat} />
        <T.Mesh geometry={gltf.nodes.eUDWuQsIBzQvKnr.geometry} material={gltf.materials.WwsbjWsUTqkHjyi} />
        <T.Mesh geometry={gltf.nodes.fbQSAObXlAFNrTB.geometry} material={gltf.materials.lIkeUCuAgtmXqMm} />
        <T.Mesh geometry={gltf.nodes.axhbofBzrcPHGNC.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.jqzyDcfEWAObzqu.geometry} material={gltf.materials.DDTdMXfdNuiuuKY} />
        <T.Mesh geometry={gltf.nodes.FtCJydnXEwfnYhk.geometry} material={gltf.materials.lxyVilivCNAAGIX} />
        <T.Mesh geometry={gltf.nodes.yOxTAdtHcqpJQcW.geometry} material={gltf.materials.bPkZQEigsToYyEb} />
        <T.Mesh geometry={gltf.nodes.oNdwLsAMWeVFRHb.geometry} material={gltf.materials.DDTdMXfdNuiuuKY} />
        <T.Mesh geometry={gltf.nodes.IVUmCkeCMrNjWyf.geometry} material={gltf.materials.nZERQganZbJSuaU} />
        <T.Mesh geometry={gltf.nodes.oAWGNgCNjsdFObV.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.iURsiFzEXHjnluF.geometry} material={gltf.materials.XXuRSphlgMABayB} />
        <T.Mesh geometry={gltf.nodes.reGnBNbSrWUhgXY.geometry} material={gltf.materials.jaAOvxaOjFCLhAJ} />
        <T.Mesh geometry={gltf.nodes.HvOWnnRtSPSgRpp.geometry} material={gltf.materials.wvXBYkOjrrFFsaK} />
        <T.Mesh geometry={gltf.nodes.tOcnXdgRVIpvVcJ.geometry} material={gltf.materials.JzwaDHwfoQCENhb} />
        <T.Mesh geometry={gltf.nodes.ckthbUCVAlslGwo.geometry} material={gltf.materials.JzwaDHwfoQCENhb} />
        <T.Mesh geometry={gltf.nodes.BtxqtHelRBYPNjd.geometry} material={gltf.materials.DDTdMXfdNuiuuKY} />
        <T.Mesh geometry={gltf.nodes.SnqyBGRajoAqQBo.geometry} material={gltf.materials.lxyVilivCNAAGIX} />
        <T.Mesh geometry={gltf.nodes.KfqydeDluRMVncm.geometry} material={gltf.materials.bPkZQEigsToYyEb} />
        <T.Mesh geometry={gltf.nodes.opZAXkoXMVsPZfx.geometry} material={gltf.materials.DDTdMXfdNuiuuKY} />
        <T.Mesh geometry={gltf.nodes.MEOAyLvZzdtthOP.geometry} material={gltf.materials.ldlWJWPqNVGUyAp} />
        <T.Mesh geometry={gltf.nodes.cgCfUEjgOAehctg.geometry} material={gltf.materials.ldlWJWPqNVGUyAp} />
        <T.Mesh geometry={gltf.nodes.vfgqltUlweTtuUQ.geometry} material={gltf.materials.DDTdMXfdNuiuuKY} />
        <T.Mesh geometry={gltf.nodes.WsknpEXvcylrpFI.geometry} material={gltf.materials.ldlWJWPqNVGUyAp} />
        <T.Mesh geometry={gltf.nodes.ySPUcfDKfrAJDkd.geometry} material={gltf.materials.nZERQganZbJSuaU} />
        <T.Mesh geometry={gltf.nodes.sbwBuXGlPZUuZhO.geometry} material={gltf.materials.XXuRSphlgMABayB} />
        <T.Mesh geometry={gltf.nodes.eHkjmMEdCbNTHKq.geometry} material={gltf.materials.jaAOvxaOjFCLhAJ} />
        <T.Mesh geometry={gltf.nodes.CvblWIuOYCeiubv.geometry} material={gltf.materials.wvXBYkOjrrFFsaK} />
        <T.Mesh geometry={gltf.nodes.LiHxzBeBpnvPmqv.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.zEbqYwxrZLBpGwY.geometry} material={gltf.materials.DDTdMXfdNuiuuKY} />
        <T.Mesh geometry={gltf.nodes.EHsIAxvaWewKLkj.geometry} material={gltf.materials.bPkZQEigsToYyEb} />
        <T.Mesh geometry={gltf.nodes.cVSOhwynzuPTTad.geometry} material={gltf.materials.lxyVilivCNAAGIX} />
        <T.Mesh geometry={gltf.nodes.qXTORrocXUUDbdL.geometry} material={gltf.materials.XXuRSphlgMABayB} />
        <T.Mesh geometry={gltf.nodes.ronXuqOovjTriZk.geometry} material={gltf.materials.jaAOvxaOjFCLhAJ} />
        <T.Mesh geometry={gltf.nodes.ITpkaLmvkfCQQze.geometry} material={gltf.materials.wvXBYkOjrrFFsaK} />
        <T.Mesh geometry={gltf.nodes.LHYUrIgekAZIxJn.geometry} material={gltf.materials.sBkPLofgPxutogi} />
        <T.Mesh geometry={gltf.nodes.gYxafxocoIVEaqL.geometry} material={gltf.materials.nZERQganZbJSuaU} />
        <T.Mesh geometry={gltf.nodes.xUWhjfdbAkIxBFR.geometry} material={gltf.materials.JzwaDHwfoQCENhb} />
        <T.Mesh geometry={gltf.nodes.oRDDuTkmFDoOGgX.geometry} material={gltf.materials.JzwaDHwfoQCENhb} />
        <T.Mesh geometry={gltf.nodes.fzTRIqQhBOYDYUP.geometry} material={gltf.materials.otyzQKWDmEsmWNb} />
        <T.Mesh geometry={gltf.nodes.ETycAkqXtCPSWAW.geometry} material={gltf.materials.otyzQKWDmEsmWNb} />
        <T.Mesh geometry={gltf.nodes.bYbpdLBDipjTqaD.geometry} material={gltf.materials.KtouhvwQzJWWPrE} />
        <T.Mesh geometry={gltf.nodes.cZZMbxHbRDozLKa.geometry} material={gltf.materials.nYXuzwbAXKNwVVk} />
        <T.Mesh geometry={gltf.nodes.fBQkcXlqdumyuPk.geometry} material={gltf.materials.XoueRDhbsAsbeTf} />
        <T.Mesh geometry={gltf.nodes.rQfrWUmmticZJhs.geometry} material={gltf.materials.bUGYdGWBIxjsKUI} />
        <T.Mesh geometry={gltf.nodes.QQmFWgkRfIVTarZ.geometry} material={gltf.materials.BIXrNIXlGLRYyov} />
        <T.Mesh geometry={gltf.nodes.JFHvDbfOkQKwrQt.geometry} material={gltf.materials.yCRJxqsYVHIqsxx} />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
