<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/Tesseract.glb --types
Author: EmersonCaon (https://sketchfab.com/EmersonCaon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tesseract-20-d5995edaf25e4331b7fb7f50470feddd
Title: Tesseract 2.0
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Acao'
  type GLTFResult = {
    nodes: {
      Object_7: THREE.SkinnedMesh
      Object_8: THREE.SkinnedMesh
      Object_9: THREE.SkinnedMesh
      GLTF_created_0_rootJoint: THREE.Bone
    }
    materials: {
      TesseractAzul: THREE.MeshPhysicalMaterial
      TesseractRoxo: THREE.MeshPhysicalMaterial
      TesseractVernelho: THREE.MeshPhysicalMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/static/models/Tesseract.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
  
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="Ossos_5" position={[0, 1.27, 0]}>
              <T.Group name="GLTF_created_0">
                <T is={gltf.nodes.GLTF_created_0_rootJoint} />
                <T.Group name="Cube_4" />
                <T.SkinnedMesh
                  name="Object_7"
                  geometry={gltf.nodes.Object_7.geometry}
                  material={gltf.materials.TesseractAzul}
                  skeleton={gltf.nodes.Object_7.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_8"
                  geometry={gltf.nodes.Object_8.geometry}
                  material={gltf.materials.TesseractRoxo}
                  skeleton={gltf.nodes.Object_8.skeleton}
                />
                <T.SkinnedMesh
                  name="Object_9"
                  geometry={gltf.nodes.Object_9.geometry}
                  material={gltf.materials.TesseractVernelho}
                  skeleton={gltf.nodes.Object_9.skeleton}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
